### ISSUE TITLE
don't works returntype json and array

### ISSUE THREAD

**Issue by vladimirkprog** [saddamrhossain/namecheap-sdk#9]
xml response on wich function convert works incorrect.

`<?xml version="1.0" encoding="utf-8"?>
<ApiResponse Status="OK" xmlns="http://api.namecheap.com/xml.response">
  <Errors />
  <Warnings />
  <RequestedCommand>namecheap.domains.check</RequestedCommand>
  <CommandResponse Type="namecheap.domains.check">
    <DomainCheckResult Domain="mynewdomain11111122223.com" Available="true" ErrorNo="0" Description="" IsPremiumName="false" PremiumRegistrationPrice="0" PremiumRenewalPrice="0" PremiumRestorePrice="0" PremiumTransferPrice="0" IcannFee="0" EapFee="0.0" />
  </CommandResponse>
  <Server>PHX01SBAPIEXT02</Server>
  <GMTTimeDifference>--5:00</GMTTimeDifference>
  <ExecutionTime>0.555</ExecutionTime>
</ApiResponse>`

mistake in vendor/saddamrhossain/namecheap-sdk/src/Namecheap/Xml.php in function convert  line 117

`
if (!is_array($output) && !empty($output)) {
                        //ok
                    } else {
                          // here $output is a string for DomainCheckResult  element. So all attributes doesnt will apppear in a result
                        foreach ($a as $k => $v) {
                            $output['_'.$k] = $v;       // wrong output - trying to set as array into a string
                        }
                    }

`

**Comment by saddamrhossain** [comment]
Here is the output of the above XML result using the Xml class
```json
{
  "ApiResponse": {
    "Errors": "",
    "Warnings": "",
    "RequestedCommand": "namecheap.domains.check",
    "CommandResponse": {
      "DomainCheckResult": {
        "_Domain": "mynewdomain11111122223.com",
        "_Available": "true",
        "_ErrorNo": "0",
        "_Description": "",
        "_IsPremiumName": "false",
        "_PremiumRegistrationPrice": "0",
        "_PremiumRenewalPrice": "0",
        "_PremiumRestorePrice": "0",
        "_PremiumTransferPrice": "0",
        "_IcannFee": "0",
        "_EapFee": "0.0"
      },
      "_Type": "namecheap.domains.check"
    },
    "Server": "PHX01SBAPIEXT02",
    "GMTTimeDifference": "--5:00",
    "ExecutionTime": "0.555",
    "_Status": "OK"
  }
}
```

Also,
```php
$arr[key] = value;
```
If $arr doesn't exist yet, it will be created. (but this practice is however discouraged because if $arr already contains some value (e.g. string from request variable) then this value will stay in the place).

However, in our case, the `$output` will be an array or an empty string and there should not be any issue. 

Therefore, I need more information regarding your question.

**Comment by vladimirkprog** [comment]
I'm sorry for delay. I aggree in xml response all is ok. I got available status and others. But when it is converted in json or array (I specified option 'json' or 'array' in your library) then new response object doesnt contain these attributes. Yes object have type, what I set but all important information doesnt available in this case. So I can use only xml response and I need to provide my own method to fetch all information from xml.

**Comment by vladimirkprog** [comment]
I tried a simple code http://sandbox.onlinephpfunctions.com/
`
$some = '';
$some[] = 'some';
print_r($some);
`
and got fatal error for version php 7.1.0 and 7.2.4. All other versions was ok. On my local server php version was 7.1.23. So I think it is an issue, not a question. Please check.

**Comment by vladimirkprog** [comment]
in vendor/saddamrhossain/namecheap-sdk/src/Namecheap/Xml.php on line 100 
$output = '';
and then after 
$output['_'.$k] = $v; // just fails to set a properties
